blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentsView

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog-list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('add/comment/<int:pk>/', CommentsView.as_view(), name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('', include('blog.urls')),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('', include('order.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, AboutUsView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about-us/', AboutUsView.as_view(), name='about-us')
]

order/urls.py
from django.urls import path
from .views import CheckoutView, OrderHistoryView

app_name = 'order'

urlpatterns = [
    path('orider/history/', OrderHistoryView.as_view(), name='history'),
    path('checkout/', CheckoutView.as_view(), name='checkout')
]

product/urls.py
from django.urls import path
from .views import ShopListView, ProductDetailView, wishlist_view, WishlistView, cart_view, ShoppingCartView

app_name = 'product'

urlpatterns = [
    path('shopping_cart/', ShoppingCartView.as_view(), name='shopping_cart'),
    path('add_cart/<int:id>/', cart_view, name='cart'),
    path('wishlist/', WishlistView.as_view(), name='wishlist_list'),
    path('wishlist/<int:id>/', wishlist_view, name='wishlist'),
    path('shop/', ShopListView.as_view(), name='shop'),
    path('shop/<int:pk>/', ProductDetailView.as_view(), name='detail')
]

blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField


class AuthorModel(models.Model):
    first_name = models.CharField(max_length=100, verbose_name=_('first name'))
    last_name = models.CharField(max_length=100, verbose_name=_('last name'))
    image = models.ImageField(upload_to='authors/')

    @property
    def get_fullname(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.get_fullname

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class TagsModel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class BlogModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    body = RichTextField(verbose_name=_('body'))
    main_image = models.ImageField(upload_to='blogs/', verbose_name=_('main image'))
    banner_image = models.ImageField(upload_to='blogs/', verbose_name=_('banner image'))
    tags = models.ManyToManyField(TagsModel, verbose_name=_('tag'), related_name='blogs')
    author = models.ForeignKey(AuthorModel, on_delete=models.RESTRICT, verbose_name=_('author'), related_name='blogs')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('blog')
        verbose_name_plural = _('blogs')


class CommentsModel(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))
    blog = models.ForeignKey(BlogModel, on_delete=models.RESTRICT)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class ContactModel(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    message = models.TextField(verbose_name=_('message'))

    class Meta:
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')

blog/forms.py
from django import forms
from .models import CommentsModel


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentsModel
        fields = ['name', 'email', 'phone', 'comment']

blog/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import BlogModel, TagsModel, CommentsModel
from .forms import CommentForm


class CommentsView(CreateView):
    model = CommentsModel
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.blog = get_object_or_404(BlogModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', kwargs={"pk": self.kwargs.get('pk')})


class BlogDetailView(DetailView):
    model = BlogModel
    template_name = 'main/blog-details.html'

    def get_context_data(self, **kwargs):
        data = super(BlogDetailView, self).get_context_data(**kwargs)
        data['comments'] = CommentsModel.objects.all().filter(blog=self.kwargs.get('pk')).order_by('-id')
        return data

class BlogListView(ListView):
    template_name = 'main/blog.html'

    def get_queryset(self):
        qs = BlogModel.objects.all()
        tag = self.request.GET.get('tag', '')
        if tag and tag.isdigit():
            tmp = TagsModel.objects.all().filter(id=tag).exists()
            if tmp:
                qs = qs.filter(tags=tag)

        return qs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        tag = self.request.GET.get('tag', '')
        if tag and tag.isdigit():
            tmp = TagsModel.objects.all().filter(id=tag).exists()
            if tmp:
                data['tag'] = TagsModel.objects.get(id=tag)

        return data

main/views.py
from django.shortcuts import render, reverse
from django.views.generic import TemplateView, CreateView
from .models import ContactModel


class AboutUsView(TemplateView):
    template_name = 'main/about.html'

class ContactView(CreateView):
    model = ContactModel
    fields = ['name', 'email', 'message']
    template_name = 'main/contact.html'

    def get_success_url(self):
        return reverse('contact')

class HomeView(TemplateView):
    template_name = 'main/index.html'

templates/main/blog.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'main/img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if tag %}
                        <h2>#{{ tag.name }}</h2>
                    {% else %}
                        <h2>Our Blog</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for object in object_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg"
                                 data-setbg="{{ object.main_image.url }}"></div>
                            <div class="blog__item__text">
                                <span><img src="{% static 'main/img/icon/calendar.png' %}"
                                           alt="">{{ object.created_at|date:"d F Y" }}</span>
                                <h5>{{ object.title }}</h5>
                                <a href="{% url 'blog:detail' pk=object.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock %}

templates/main/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/main/order-history.html
{% extends 'layouts/base.html' %}
{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Check Out</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <span>Order history</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Products</th>
                        <th scope="col">Total price</th>
                        <th scope="col">Created at</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>
                                <ul>
                                    {% for product in object.products.all %}
                                        <li>{{ product.name }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                            <td>{{ object.total_price }}</td>
                            <td>{{ object.created_at }}</td>
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
            </div>
        </div>
    </div>



{% endblock %}

templates/main/shop.html
{% extends 'layouts/base.html' %}
{% load static my_tags %}
{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include 'layouts/sidebar.html' %}
                </div>
                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing {{ page_obj.start_index }} – {{ page_obj.end_index }}
                                        of {{ page_obj.paginator.count }} results</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select onchange="addParam('sort', this.value)">
                                        <option value="" {% if request.GET.sort == '' %}
                                                selected
                                        {% endif %}>-----
                                        </option>
                                        <option value="real_price" {% if request.GET.sort == 'real_price' %}
                                                selected
                                        {% endif %} >Low To High
                                        </option>
                                        <option value="-real_price" {% if request.GET.sort == '-real_price' %}
                                                selected
                                        {% endif %}>High To Low
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for object in object_list %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{ object.main_image.url }}">
                                        {% if object.is_new %}
                                            <span class="label">New</span>
                                        {% endif %}
                                        {% if object.is_discount %}
                                            <span class="label {% if object.is_new %}
                                    mt-4
                                    {% endif %} " style="background-color: black; color: white;">Sale</span>
                                        {% endif %}
                                        <ul class="product__hover">
                                            {% if request.user.is_authenticated %}
                                                {% is_wishlist request object as obj %}
                                                {% if obj %}
                                                    <li>
                                                        <a href="{% url 'product:wishlist' object.id %}?path={{ request.path }}"><img
                                                                src="{% static 'main/img/heart.png' %}"
                                                                alt=""></a></li>
                                                {% else %}
                                                    <li>
                                                        <a href="{% url 'product:wishlist' object.id %}?path={{ request.path }}"><img
                                                                src="{% static 'main/img/icon/heart.png' %}"
                                                                alt=""></a></li>
                                                {% endif %}
                                            {% endif %}

                                            <li><a href="{% url 'product:detail' pk=object.pk %}"><img
                                                    src="{% static 'main/img/icon/search.png' %}"
                                                    alt=""></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <h6>{{ object.name }}</h6>

                                        {% is_cart request object.id as value %}
                                        {% if value %}
                                            <a href="{% url 'product:cart' id=object.id %}?next={{ request.path }}"
                                               class="add-cart" style="color: black;">
                                                - Remove from cart
                                            </a>
                                        {% else %}
                                            <a href="{% url 'product:cart' id=object.id %}?next={{ request.path }}"
                                               class="add-cart">
                                                + Add To Cart
                                            </a>
                                        {% endif %}
                                        <div class="rating">
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                        </div>
                                        <h5>${% if object.is_discount %}
                                            {{ object.real_price }}
                                            <del class="text-secondary">${{ object.price }}</del>
                                        {% else %}
                                            {{ object.real_price }}
                                        {% endif %}
                                        </h5>
                                        <div class="product__color__select">
                                            {% for color in object.color.all %}
                                                <label for="pc-4" style="background-color: {{ color.code }}">
                                                    <input type="radio" id="pc-4">
                                                </label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product__pagination">
                                {% if not page_obj.paginator.count < 10 %}
                                    {% paginator_range paginator as p_range %}
                                    {% for page in p_range %}

                                        <a href="?page={{ page }}" class="{% if page_obj.number == page %}
                                    active
                                    {% endif %}">{{ page }}</a>
                                    {% endfor %}

                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->
{% endblock %}

{% block extra_js %}
    <script>
        {% get_price request as price %}
        $(".js-range-slider").ionRangeSlider({
            type: "double",
            grid: true,
            min: {{ min }},
            max: {{ max }},
            from: {{ price.0|default:'null' }},
            to: {{ price.1|default:'null' }},
            prefix: "$",
            onFinish: function (data) {
                addParam('price', data.from.toString() + ";" + data.to.toString())
            }
        });

        function addParam(name, value) {
            var param = new URLSearchParams(window.location.search)
            if (param.has(name) && param.get(name) == value) {
                param.delete(name)
            } else {
                param.set(name, value)
            }
            window.location.search = param.toString()
        }
    </script>
{% endblock %}

templates/main/shopping-cart.html
{% extends 'layouts/base.html' %}
{% load static my_tags %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <a href="{% url 'product:shop' %}">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for object in object_list %}
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img src="{{ object.main_image.url }}" alt="" width="90" height="90">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{ object.name }}</h6>
                                            <h5>${{ object.real_price }}</h5>
                                        </div>
                                    </td>
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input type="text" value="1">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="cart__price">$ 30.00</td>
                                    <td class="cart__close"><a href="{% url 'product:cart' id=object.id %}?next={{ request.path }}"><i
                                            class="fa fa-close"></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            {% cart_info request as info %}
                            <li>Total <span>$ {{ info.1 }}</span></li>
                        </ul>
                        <a href="{% url 'order:checkout' %}" class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->

{% endblock %}

templates/main/wishlist.html
{% extends 'layouts/base.html' %}
{% load static my_tags %}
{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <span>Wishlist</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing {{ page_obj.start_index }} – {{ page_obj.end_index }}
                                        of {{ page_obj.paginator.count }} results</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for object in object_list %}
                            <div class="col-lg-3 col-md-4 col-sm-6">
                                <div class="product__item">
                                    <div class="product__item__pic set-bg" data-setbg="{{ object.product.main_image.url }}">
                                        {% if object.product.is_new %}
                                            <span class="label">New</span>
                                        {% endif %}
                                        {% if object.product.is_discount %}
                                            <span class="label {% if object.product.is_new %}
                                    mt-4
                                    {% endif %} " style="background-color: black; color: white;">Sale</span>
                                        {% endif %}
                                        <ul class="product__hover">
                                            {% is_wishlist request object.product.id as obj %}
                                            {% if request.user.is_authenticated %}
                                                {% if obj %}
                                                    <li>
                                                        <a href="{% url 'product:wishlist' object.product.id %}?path={{ request.path }}"><img
                                                                src="{% static 'main/img/heart.png' %}"
                                                                alt=""></a></li>
                                                {% else %}
                                                    <li>
                                                        <a href="{% url 'product:wishlist' object.product.id %}?path={{ request.path }}"><img
                                                                src="{% static 'main/img/icon/heart.png' %}"
                                                                alt=""></a></li>
                                                {% endif %}
                                            {% endif %}

                                            <li><a href="{% url 'product:detail' pk=object.product.pk %}"><img
                                                    src="{% static 'main/img/icon/search.png' %}"
                                                    alt=""></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <h6>{{ object.product.name }}</h6>
                                        <a href="#" class="add-cart">+ Add To Cart</a>
                                        <div class="rating">
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                        </div>
                                        <h5>${% if object.product.is_discount %}
                                            {{ object.product.real_price }}
                                            <del class="text-secondary">${{ object.product.price }}</del>
                                        {% else %}
                                            {{ object.product.real_price }}
                                        {% endif %}
                                        </h5>
                                        <div class="product__color__select">
                                            {% for color in object.product.color.all %}
                                                <label for="pc-4" style="background-color: {{ color.code }}">
                                                    <input type="radio" id="pc-4">
                                                </label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <h1>Empty</h1>
                        {% endfor %}

                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product__pagination">
                                {% if not page_obj.paginator.count < 13 %}
                                    {% paginator_range paginator as p_range %}
                                    {% for page in p_range %}

                                        <a href="?page={{ page }}" class="{% if page_obj.number == page %}
                                    active
                                    {% endif %}">{{ page }}</a>
                                    {% endfor %}

                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->
{% endblock %}