blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentsView

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog-list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('add/comment/<int:pk>/', CommentsView.as_view(), name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('', include('blog.urls')),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('', include('order.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, AboutUsView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about-us/', AboutUsView.as_view(), name='about-us')
]

order/urls.py
from django.urls import path
from .views import CheckoutView, OrderHistoryView

app_name = 'order'

urlpatterns = [
    path('orider/history/', OrderHistoryView.as_view(), name='history'),
    path('checkout/', CheckoutView.as_view(), name='checkout')
]

product/urls.py
from django.urls import path
from .views import ShopListView, ProductDetailView, wishlist_view, WishlistView, cart_view, ShoppingCartView

app_name = 'product'

urlpatterns = [
    path('shopping_cart/', ShoppingCartView.as_view(), name='shopping_cart'),
    path('add_cart/<int:id>/', cart_view, name='cart'),
    path('wishlist/', WishlistView.as_view(), name='wishlist_list'),
    path('wishlist/<int:id>/', wishlist_view, name='wishlist'),
    path('shop/', ShopListView.as_view(), name='shop'),
    path('shop/<int:pk>/', ProductDetailView.as_view(), name='detail')
]

users/urls.py
from django.urls import path
from .views import login_view, logout_view, registration, ProfileView

app_name = 'users'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name="profile"),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration, name='registration')
]

templates/layouts/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/login/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/fonts/icomoon/style.css' %}">

</head>

<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>
{% include 'layouts/navbar.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" action="{% url 'product:shop' %}" method="get">
            <input type="text" id="search-input" value="{{ request.GET.q }}" name="q" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{% static 'main/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'main/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'main/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'main/js/mixitup.min.js' %}"></script>
<script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
<script src="{% static 'main/js/login/main.js' %}"></script>
<script src="{% static 'main/js/login/popper.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
{% block extra_js %}

{% endblock %}
</body>

</html>

templates/layouts/footer.html
{% load static %}
<!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'main/img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes design.</p>
                        <a href="#"><img src="{% static 'main/img/payment.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Clothing Store</a></li>
                            <li><a href="#">Trending Shoes</a></li>
                            <li><a href="#">Accessories</a></li>
                            <li><a href="#">Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Delivary</a></li>
                            <li><a href="#">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                       <p>text</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

templates/layouts/navbar.html
{% load static my_tags i18n %}
{% cart_info request as cart_info %}
<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="#">Sign in</a>
            <a href="#">FAQs</a>
        </div>
        <div class="offcanvas__top__hover">
            <span>Usd <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>USD</li>
                <li>EUR</li>
                <li>USD</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">

    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">

                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'users:logout' %}">Log out</a>
                                <a href="{% url 'users:profile' %}">Profile</a>
                                <a href="{% url 'order:history' %}">Order history</a>
                                <a href="#">{{ request.user }}</a>
                            {% else %}
                                <a href="{% url 'users:login' %}">Sign in</a>
                            {% endif %}

                        </div>
                        <div class="header__top__hover">
                            <span>{% get_current_language as lan %}{{ lan }} <i class="arrow_carrot-down"></i></span>
                            <ul>
                                {% get_available_languages as languages %}
                                {% for language in languages %}
                                    <li style="{% if language.0 == lan %}
                                        background-color: black; width: 100%;
                                    {% endif %} "><a href="/{{ language.0 }}/{{ request.path|slice:'4:' }}"
                                                     style="{% if language.0 == lan %}
                                                         color: white;
                                                     {% else %}
                                                         color: black;
                                                     {% endif %} ">{{ language.1 }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="./index.html"><img src="{% static 'main/img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        {% url 'main:home' as path %}
                        <li class="{% if path == request.path %}
                        active
                        {% endif %} "><a href="{% url 'main:home' %}">Home</a></li>
                        {% url 'product:shop' as path %}
                        <li class="{% if path == request.path %}
                        active
                        {% endif %} "><a href="{% url 'product:shop' %}">Shop</a></li>
                        {% url 'blog:blog-list' as path %}
                        <li class="{% if path == request.path %}
                        active
                        {% endif %} "><a href="{% url 'blog:blog-list' %}">Blog</a></li>
                        {% url 'main:about-us' as path %}
                        <li class="{% if path == request.path %}
                        active
                        {% endif %} "><a href="{% url 'main:about-us' %}">About us</a></li>
                        {% url 'main:contact' as path %}
                        <li class="{% if path == request.path %}
                        active
                        {% endif %} "><a href="{% url 'main:contact' %}">Contacts</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png' %}" alt=""></a>
                    <a href="{% url 'product:wishlist_list' %}"><img src="{% static 'main/img/icon/heart.png' %}"
                                                                     alt=""></a>
                    <a href="{% url 'product:shopping_cart' %}"><img src="{% static 'main/img/icon/cart.png' %}" alt="">
                        <span>{{ cart_info.0 }}</span></a>
                    <div class=" price">${{ cart_info.1 }}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/sidebar.html
{% load static my_tags %}

<div class="shop__sidebar">
    <div class="shop__sidebar__search">
        <form action="#" method="get">
            <input type="text" placeholder="Search..." name="q" value="{{ request.GET.q }}">
            <button type="submit"><span class="icon_search"></span></button>
        </form>
        <a href="{% url 'product:shop' %}" class="clear_search">Clear search</a>
    </div>
    <div class="shop__sidebar__accordion">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__categories">
                            <ul class="nice-scroll">
                                {% for category in categories %}
                                    <li><a href="#"
                                           onclick="addParam('cat', {{ category.id }})"
                                           class="{% if category.id == request.GET.cat|change_type_int %}
                                            text-dark
                                           {% endif %} ">{{ category.name|capfirst }}
                                        ({{ category.products.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                </div>
                <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__brand">
                            <ul>
                                {% for brand in brands %}
                                    <li><a href="#" class="{% if brand.id == request.GET.brand|change_type_int %}
                                        text-dark
                                    {% endif %} "
                                           onclick="addParam('brand', {{ brand.id }})">{{ brand.name|capfirst }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                </div>
                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__price">
                            <input type="text" class="js-range-slider" name="my_range" value=""/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__size">
                            {% for size in sizes %}
                                <label for="{{ size.size }}" class="{% if size.id == request.GET.size|change_type_int %}
                                    active
                                {% endif %} ">{{ size.size }}
                                    <input type="radio" id="{{ size.size }}" onchange="addParam('size', {{ size.id }})">
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                </div>
                <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__color">
                            {% for color in colors %}
                                <a href="#" onclick="addParam('color', {{ color.id }})" style="background-color: {{ color.code }};"
                                        class="{% if color.id == request.GET.color|change_type_int %}
                                active
                                {% endif %} ">
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            {% for tag in tags %}
                                <a href="#" class="{% if tag.id == request.GET.tag|change_type_int %}
                                    my_active
                                {% endif %} " onclick="addParam('tag', {{ tag.id }})">{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>