blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentsView

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog-list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('add/comment/<int:pk>/', CommentsView.as_view(), name='comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('', include('blog.urls')),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('', include('order.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import login_view, logout_view, registration, ProfileView

app_name = 'users'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name="profile"),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration, name='registration')
]

templates/login/index.html
{% extends 'layouts/base.html' %}

{% load static %}
{% block content %}
    <div class="d-md-flex half">
        <div class="bg" style="background-image: url({% static 'main/img/bg_1.jpg' %});"></div>
        <div class="contents">

            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="form-block mx-auto">
                            <div class="text-center mb-5">
                                <h3 class="text-uppercase">Login</h3>
                            </div>
                            <form action="#" method="post">
                                {% csrf_token %}
                                <div class="form-group first">
                                    <label for="username">Username</label>
                                    {{ form.username }}
                                    {% for error in form.username.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="form-group last mb-3">
                                    <label for="password">Password</label>
                                    {{ form.password }}
                                    {% for error in form.password.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>

                                <div class="d-sm-flex mb-5 align-items-center">
                                    <label class="control control--checkbox mb-3 mb-sm-0 p-0">
                                        <a href="{% url 'users:registration' %}">Registration</a>
                                    </label>
                                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                </div>

                                <input type="submit" value="Log In" class="btn btn-block py-2 btn-primary">

                                <span class="text-center my-3 d-block">or</span>


                                <div class="">
                                    <a href="#" class="btn btn-block py-2 btn-facebook">
                                        <span class="icon-facebook mr-3"></span> Login with facebook
                                    </a>
                                    <a href="#" class="btn btn-block py-2 btn-google"><span
                                            class="icon-google mr-3"></span> Login with Google</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>


{% endblock %}

templates/login/registration.html
{% extends 'layouts/base.html' %}

{% load static %}
{% block content %}
    <div class="d-md-flex half">
        <div class="bg" style="background-image: url({% static 'main/img/bg_1.jpg' %});"></div>
        <div class="contents">

            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="form-block mx-auto">
                            <div class="text-center mb-5">
                                <h3 class="text-uppercase">Registration</h3>
                            </div>
                            <form action="#" method="post">
                                {% csrf_token %}
                                <div class="form-group first">
                                    <label for="username">Username</label>
                                    {{ form.username }}
                                    {% for error in form.username.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="form-group last mb-3">
                                    <label for="password">Password</label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group last mb-3">
                                    <label for="password">Confirm Password</label>
                                    {{ form.confirm_password }}
                                    {% for error in form.confirm_password.errors %}
                                        <span style="color: red;">{{ error }}</span>
                                    {% endfor %}

                                </div>

                                <div class="d-sm-flex mb-5 align-items-center">
                                    <label class="control control--checkbox mb-3 p-0 mb-sm-0">
                                        <a href="{% url 'users:login' %}">Login</a>
                                    </label>
                                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                                </div>

                                <button type="submit" class="btn btn-block py-2 btn-primary">Save</button>

                                <span class="text-center my-3 d-block">or</span>


                                <div class="">
                                    <a href="#" class="btn btn-block py-2 btn-facebook">
                                        <span class="icon-facebook mr-3"></span> Login with facebook
                                    </a>
                                    <a href="#" class="btn btn-block py-2 btn-google"><span
                                            class="icon-google mr-3"></span> Login with Google</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>


{% endblock %}